/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface ExtensionInterface extends utils.Interface {
  functions: {
    "addCertificateSigner(address,address)": FunctionFragment;
    "registerTokenSetup(address,uint8,bool,bool,bool,bool,address[])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "addCertificateSigner" | "registerTokenSetup"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addCertificateSigner",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "registerTokenSetup",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>,
      PromiseOrValue<boolean>,
      PromiseOrValue<boolean>,
      PromiseOrValue<boolean>,
      PromiseOrValue<string>[]
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "addCertificateSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerTokenSetup",
    data: BytesLike
  ): Result;

  events: {};
}

export interface Extension extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ExtensionInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addCertificateSigner(
      token: PromiseOrValue<string>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    registerTokenSetup(
      token: PromiseOrValue<string>,
      certificateActivated: PromiseOrValue<BigNumberish>,
      allowlistActivated: PromiseOrValue<boolean>,
      blocklistActivated: PromiseOrValue<boolean>,
      granularityByPartitionActivated: PromiseOrValue<boolean>,
      holdsActivated: PromiseOrValue<boolean>,
      operators: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  addCertificateSigner(
    token: PromiseOrValue<string>,
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  registerTokenSetup(
    token: PromiseOrValue<string>,
    certificateActivated: PromiseOrValue<BigNumberish>,
    allowlistActivated: PromiseOrValue<boolean>,
    blocklistActivated: PromiseOrValue<boolean>,
    granularityByPartitionActivated: PromiseOrValue<boolean>,
    holdsActivated: PromiseOrValue<boolean>,
    operators: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addCertificateSigner(
      token: PromiseOrValue<string>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    registerTokenSetup(
      token: PromiseOrValue<string>,
      certificateActivated: PromiseOrValue<BigNumberish>,
      allowlistActivated: PromiseOrValue<boolean>,
      blocklistActivated: PromiseOrValue<boolean>,
      granularityByPartitionActivated: PromiseOrValue<boolean>,
      holdsActivated: PromiseOrValue<boolean>,
      operators: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    addCertificateSigner(
      token: PromiseOrValue<string>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    registerTokenSetup(
      token: PromiseOrValue<string>,
      certificateActivated: PromiseOrValue<BigNumberish>,
      allowlistActivated: PromiseOrValue<boolean>,
      blocklistActivated: PromiseOrValue<boolean>,
      granularityByPartitionActivated: PromiseOrValue<boolean>,
      holdsActivated: PromiseOrValue<boolean>,
      operators: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addCertificateSigner(
      token: PromiseOrValue<string>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    registerTokenSetup(
      token: PromiseOrValue<string>,
      certificateActivated: PromiseOrValue<BigNumberish>,
      allowlistActivated: PromiseOrValue<boolean>,
      blocklistActivated: PromiseOrValue<boolean>,
      granularityByPartitionActivated: PromiseOrValue<boolean>,
      holdsActivated: PromiseOrValue<boolean>,
      operators: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
